require 'yaml'

# APIFixtures loads fixture data generated by the core Stripe API so that we
# can have slightly more accurate and up-to-date resource information in our
# tests.
class APIFixtures
  def initialize
    @fixtures = ::YAML.load(
      File.read("#{PROJECT_ROOT}/openapi/fixtures.yaml"),
      symbolize_names: true
    )["resources"]
    @manual_fixtures = ::YAML.load(
      File.read("#{PROJECT_ROOT}/test/manual_fixtures.yaml"),
      symbolize_names: true
    )["resources"]

    # Note that this is not a recursive merge: only new resources that are not
    # in the main fixtures file will end up in the product.
    @fixtures.merge!(@manual_fixtures)

    @fixtures = Stripe::Util.symbolize_names(@fixtures)

    freeze_recursively(@fixtures)
  end

  def [](name)
    @fixtures[name]
  end

  def fetch(*args)
    @fixtures.fetch(*args)
  end

  private

  def freeze_recursively(data)
    data.each do |k, v|
      if v.is_a?(Hash)
        freeze_recursively(v)
      end
    end
    data.freeze
  end
end
