# File generated from our OpenAPI spec
# frozen_string_literal: true

module Stripe
  module Events
    # Occurs when a billing Cadence generates an invoice.
    class V2BillingCadenceBilledEvent < Stripe::V2::Event
      def self.lookup_type
        "v2.billing.cadence.billed"
      end

      class V2BillingCadenceBilledEventData < Stripe::StripeObject
        # The IDs of the invoices that were generated by the tick for this Cadence.
        attr_reader :invoices

        def self.inner_class_types
          @inner_class_types = {}
        end

        def self.field_remappings
          @field_remappings = {}
        end
      end

      def self.inner_class_types
        @inner_class_types = { data: V2BillingCadenceBilledEventData }
      end
      attr_reader :data, :related_object

      # Retrieves the related object from the API. Makes an API request on every call.
      def fetch_related_object
        _request(
          method: :get,
          path: related_object.url,
          base_address: :api,
          opts: { stripe_context: context }
        )
      end
    end

    # Occurs when a billing Cadence generates an invoice.
    class V2BillingCadenceBilledEventNotification < Stripe::V2::EventNotification
      def self.lookup_type
        "v2.billing.cadence.billed"
      end

      attr_reader :related_object

      # Retrieves the Cadence related to this EventNotification from the Stripe API. Makes an API request on every call.
      def fetch_related_object
        resp = @client.raw_request(
          :get,
          related_object.url,
          opts: { stripe_context: context },
          usage: ["fetch_related_object"]
        )
        @client.deserialize(resp.http_body, api_mode: Util.get_api_mode(related_object.url))
      end
    end
  end
end
