inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/LineLength:
  Exclude:
    - "test/**/*.rb"

Metrics/MethodLength:
  # There's ~2 long methods in `StripeClient`. If we want to truncate those a
  # little, we could move this to be closer to ~30 (but the default of 10 is
  # probably too short).
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
