inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

# This can be re-enabled once we're 2.3+ only and can use the squiggly heredoc
# operator. Prior to that, Rubocop recommended bringing in a library like
# ActiveSupport to get heredoc indentation, which is just terrible.
Layout/IndentHeredoc:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"

Metrics/LineLength:
  Exclude:
    - "lib/stripe/resources/**/*.rb"
    - "test/**/*.rb"

Metrics/MethodLength:
  # There's ~2 long methods in `StripeClient`. If we want to truncate those a
  # little, we could move this to be closer to ~30 (but the default of 10 is
  # probably too short).
  Max: 50

Metrics/ModuleLength:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
