# File generated from our OpenAPI spec
# frozen_string_literal: true

module Stripe
  class QuotePreviewSubscriptionScheduleService < StripeService
    # Preview the schedules that would be generated by accepting the quote
    def list(id, params = {}, opts = {})
      request(
        method: :get,
        path: format("/v1/quotes/%<id>s/preview_subscription_schedules", { id: CGI.escape(id) }),
        params: params,
        opts: opts,
        base_address: :api
      )
    end
  end
end
