# File generated from our OpenAPI spec
# frozen_string_literal: true

module Stripe
  class QuotePreviewInvoiceService < StripeService
    # Preview the invoices that would be generated by accepting the quote.
    def list(quote, params = {}, opts = {})
      request(
        method: :get,
        path: format("/v1/quotes/%<quote>s/preview_invoices", { quote: CGI.escape(quote) }),
        params: params,
        opts: opts,
        base_address: :api
      )
    end
  end
end
