# File generated from our OpenAPI spec
# frozen_string_literal: true

module Stripe
  module V2
    module Signals
      # The PaymentRetrySignal resource represents a single retry recommendation
      # generated by the ML scoring model.
      class PaymentRetrySignal < APIResource
        OBJECT_NAME = "v2.signals.payment_retry_signal"
        def self.object_name
          "v2.signals.payment_retry_signal"
        end

        class Recommendation < ::Stripe::StripeObject
          # The recommended action to take.
          attr_reader :action
          # Human-readable reason for the recommendation.
          attr_reader :reason

          def self.inner_class_types
            @inner_class_types = {}
          end

          def self.field_remappings
            @field_remappings = {}
          end
        end
        # When this signal was created.
        attr_reader :created
        # The evaluation that generated this signal.
        attr_reader :evaluation
        # Unique identifier for the signal.
        attr_reader :id
        # Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
        attr_reader :livemode
        # String representing the object's type. Objects of the same type share the same value of the object field.
        attr_reader :object
        # The payment intent this signal relates to.
        attr_reader :payment_intent
        # The payment record this signal relates to.
        attr_reader :payment_record
        # The retry recommendation.
        attr_reader :recommendation

        def self.inner_class_types
          @inner_class_types = { recommendation: Recommendation }
        end

        def self.field_remappings
          @field_remappings = {}
        end
      end
    end
  end
end
