# File generated from our OpenAPI spec
# frozen_string_literal: true

# typed: true
module Stripe
  class QuotePreviewInvoiceService < StripeService
    # Preview the invoices that would be generated by accepting the quote.
    sig {
      params(quote: String, params: T.any(::Stripe::QuotePreviewInvoiceListParams, T::Hash[T.untyped, T.untyped]), opts: T.untyped).returns(::Stripe::ListObject)
     }
    def list(quote, params = {}, opts = {}); end
  end
end