# File generated from our OpenAPI spec
# frozen_string_literal: true

# typed: true
module Stripe
  module V2
    module Signals
      # The PaymentRetrySignal resource represents a single retry recommendation
      # generated by the ML scoring model.
      class PaymentRetrySignal < APIResource
        class Recommendation < ::Stripe::StripeObject
          # The recommended action to take.
          sig { returns(String) }
          def action; end
          # Human-readable reason for the recommendation.
          sig { returns(String) }
          def reason; end
          def self.inner_class_types
            @inner_class_types = {}
          end
          def self.field_remappings
            @field_remappings = {}
          end
        end
        # When this signal was created.
        sig { returns(String) }
        def created; end
        # The evaluation that generated this signal.
        sig { returns(String) }
        def evaluation; end
        # Unique identifier for the signal.
        sig { returns(String) }
        def id; end
        # Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
        sig { returns(T::Boolean) }
        def livemode; end
        # String representing the object's type. Objects of the same type share the same value of the object field.
        sig { returns(String) }
        def object; end
        # The payment intent this signal relates to.
        sig { returns(T.nilable(String)) }
        def payment_intent; end
        # The payment record this signal relates to.
        sig { returns(String) }
        def payment_record; end
        # The retry recommendation.
        sig { returns(Recommendation) }
        def recommendation; end
      end
    end
  end
end